// Code generated by goctl. DO NOT EDIT.
package types

type TransferReqs struct {
	From   string `form:"from"`
	To     string `form:"to"`
	Amount string `form:"amount"`
	Sign   string `form:"sign"`
}

type TransferResp struct {
	Result bool `json:"result"`
}

type NftQueryIdsReq struct {
	Address string `form:"address"`
}

type NftQueryIdsResp struct {
	Ids []int64 `form:"ids"`
}

type WoWQueryAmountReq struct {
	Address string `form:"address"`
}

type WoWQueryAmountResp struct {
	Amount string `form:"amount"`
}
