// Code generated by goctl. DO NOT EDIT.
package types

type WalletType struct {
	Type string `form:"wallet_type"` 
}

type TransferReqs struct {
	WalletType
	To     string `form:"to"` 
	Amount string `form:"amount"`
	Sign   string `form:"sign"`
}

type WithdrawReqs struct {
	Sign string `form:"sign"`
}

type TransferResp struct {
	Result bool `json:"result"` 
}

type MintNftReqs struct {
	To   string `form:"to"`     
	Id   string `form:"nft_id"` 
	Sign string `form:"sign"`
}

type NftQueryIdsReq struct {
	Address string `form:"address"`
}

type NftQueryIdsResp struct {
	Ids []int64 `form:"ids"`
}

type WoWQueryAmountReq struct {
	Address string `form:"address"`
}

type WoWQueryAmountResp struct {
	Amount string `form:"amount"`
}

type TonWalletReq struct {
	DAuthid string `form:"dauth_id"`
}

type TonWalletResp struct {
	Wallet string `json:"address"`
}
