// Code generated by goctl. DO NOT EDIT.
package types

type WithdrawReqs struct {
	Reqs string `form:"accounts"`
}

type WithdrawResp struct {
	Result bool `json:"result"`
}

type NftQueryIdsReq struct {
	Address string `form:"address"`
}

type NftQueryIdsResp struct {
	Ids []int64 `form:"ids"`
}
