// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	chain "wowfish/api/internal/handler/chain"
	chainQuery "wowfish/api/internal/handler/chainQuery"
	"wowfish/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/wowTransfer",
					Handler: chain.WowTransferHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/chain"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/queryNft",
				Handler: chainQuery.QueryNftHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/queryAmount",
				Handler: chainQuery.QueryAmountHandler(serverCtx),
			},
		},
		rest.WithPrefix("/chain"),
	)
}
