// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	chain "wowfish/api/internal/handler/chain"
	"wowfish/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/withdraw",
				Handler: chain.WithdrawHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/queryNft",
				Handler: chain.QueryNftHandler(serverCtx),
			},
		},
		rest.WithPrefix("/chain"),
	)
}
