Name: chain
Host: 0.0.0.0
Port: 8888

Chain: 
  Rpc: 
  WowToken:
  WoWNFT:
  Callback:

Kms:
  Key: 
  Secret: 
  Alias:
  GameWallet: # 
  DisposeWallet:  # 
  GainWallet: # 
  AdminWallet: # 

SecretKey: 